// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        //  Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        //  Handle this case.
        throw UnimplementedError();
    }

    /*throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );*/
  }

  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    authDomain: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    measurementId: 'xxxxxxxxxxxxxxxxxxx',
  );*/

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBMEKpxiPdc4h9jS3VClVK2_h8XA7GLmp8",
    appId: "1:757519577734:web:280cfd50802d34dd81d707",
    messagingSenderId: "757519577734",
    projectId: "tasques-novestecnologies",
    authDomain: "tasques-novestecnologies.firebaseapp.com",
    storageBucket: "tasques-novestecnologies.firebasestorage.app",
    measurementId: "G-L07HF1P5P5",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBMEKpxiPdc4h9jS3VClVK2_h8XA7GLmp8",
    appId: "1:757519577734:windows:280cfd50802d34dd81d707",
    messagingSenderId: "757519577734",
    projectId: "tasques-novestecnologies",
    storageBucket: "tasques-novestecnologies.firebasestorage.app",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBMEKpxiPdc4h9jS3VClVK2_h8XA7GLmp8",
    appId: "1:757519577734:android:81ab93e40347163d81d707",
    messagingSenderId: "757519577734",
    projectId: "tasques-novestecnologies",
    storageBucket: "tasques-novestecnologies.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );
}
