// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        //  Handle this case.
        throw UnimplementedError();
      case TargetPlatform.linux:
        //  Handle this case.
        throw UnimplementedError();
    }

    /*throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );*/
  }

  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    authDomain: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    measurementId: 'xxxxxxxxxxxxxxxxxxx',
  );*/

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBmrs9YC0Yr5ahrtuq15GRPCa4haNSethU",
    appId: "1:703255082825:web:c1b487036915e447760c98",
    messagingSenderId: "703255082825",
    projectId: "project1-aa671",
    authDomain: "project1-aa671.firebaseapp.com",
    //storageBucket: "project1-aa671.firebasestorage.app",
    storageBucket: 'project1-aa671.appspot.com',
    measurementId: "G-F28TZP3MP2",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyBmrs9YC0Yr5ahrtuq15GRPCa4haNSethU",
    appId: "1:703255082825:web:c1b487036915e447760c98",
    messagingSenderId: "703255082825",
    projectId: "project1-aa671",
    authDomain: "project1-aa671.firebaseapp.com",
    //storageBucket: "project1-aa671.firebasestorage.app",
    storageBucket: 'project1-aa671.appspot.com',
    measurementId: "G-F28TZP3MP2",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANj6UzMLVrnjRRVnOWsmCZqoyRnIIRfpU',
    appId: '1:703255082825:android:0c9ce35d188c4a2c760c98',
    messagingSenderId: '703255082825',
    projectId: 'project1-aa671',
    //databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'project1-aa671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxxxxxxxxxxxx',
    appId: 'xxxxxxxxxxxxxxxxxxx',
    messagingSenderId: 'xxxxxxxxxxxxxxxxxxx',
    projectId: 'xxxxxxxxxxxxxxxxxxx',
    databaseURL: 'xxxxxxxxxxxxxxxxxxx',
    storageBucket: 'xxxxxxxxxxxxxxxxxxx',
    androidClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosClientId: 'xxxxxxxxxxxxxxxxxxx',
    iosBundleId: 'xxxxxxxxxxxxxxxxxxx',
  );
}
